#!/usr/bin/env Rscript
#
# Run every cell of the fixture matrix through the *installed* ANCOMBC package
# and compare the result against the committed goldens.
#
# Why this exists
# ---------------
# The goldens are produced by `reference/R/harness.R`, which sources four of the
# oracle's R files and calls its internals directly, with `foreach` replaced by a
# sequential stub (`reference/R/stubs.R`). That is not the same as installing and
# running the package: the real `ancombc2()` brings its own argument checking,
# its own dispatch, and the package's own `foreach`/`%dorng%` registration.
#
# Until now that gap could not be closed, because the oracle's DESCRIPTION
# declares `Depends: R (>= 4.5.0)` and the available interpreter was 4.3.3, so
# `R CMD INSTALL` refused it. Under 4.5.x it installs, and this script is the
# check that the harness reproduces it.
#
# What it asserts
# ---------------
# For each cell: `beta` and `se` from the installed package agree with the
# committed goldens to the same contract the Rust port is held to. The
# tolerances are the ones in `crates/ancombc2-core/src/golden.rs` -- `rtol 1e-8`
# for beta/theta and `rtol 1e-7` for se/vcov -- with the same absolute floor the
# Rust side applies, `atol = max(atol, rtol * scale)`. Nothing here is loosened:
# if the real package and the harness disagree, this fails.
#
# Usage
# -----
#   R_LIBS_USER=<dir holding ANCOMBC> Rscript --vanilla scripts/verify_real_package.R
#
# Requires an R >= 4.5.0 with ANCOMBC installed, its Imports available, and the
# `jsonlite` package for reading the per-cell configs.

here <- Sys.getenv("ANCOMBC_REPO", unset = ".")
# Which golden tree to compare against. Pointing this at a tree generated by the
# harness on *this same interpreter* is the comparison that isolates the harness
# from the installed package, because it holds BLAS constant. Comparing against
# the committed goldens instead measures the BLAS difference as well -- the
# committed goldens are reference-BLAS, and an OpenBLAS R will disagree with them
# on `beta` by around 1e-06 relative, which is larger than the contract's rtol
# and for a reason that has nothing to do with the harness.
golden_root <- Sys.getenv("GOLDEN_ROOT", unset = "")
if (!nzchar(golden_root)) {
  golden_root <- file.path(here, "validation", "matrix", "golden")
}
cells <- jsonlite::fromJSON(file.path(here, "validation", "matrix", "cells.json"))$cells

if (!requireNamespace("ANCOMBC", quietly = TRUE)) {
  stop("ANCOMBC is not installed. It declares `Depends: R (>= 4.5.0)`, so this ",
       "script needs R >= 4.5.0; see docs/reproduction.md.")
}
suppressPackageStartupMessages(library(ANCOMBC))

cat(sprintf("installed ANCOMBC %s under R %s\n\n",
            as.character(packageVersion("ANCOMBC")), as.character(getRversion())))

# The per-cell configs are read with `simplifyVector = FALSE`, so a control list
# arrives as a plain list of length-1 vectors. Coerce those to scalars while
# keeping it a list, which is the shape the package's own defaults have.
`%||%` <- function(a, b) if (is.null(a)) b else a

numify <- function(x) {
  lapply(x, function(v) if (is.list(v)) numify(v) else v[[1L]])
}

# `reference/R/serialize.R` writes these with
# `writeBin(as.numeric(v), size = 8, endian = "little")`, and `as.numeric` on a
# matrix flattens in R's column-major order -- so the blob is column-major and
# must be read back that way, whatever the matrix's row and column counts are.
read_f64 <- function(path, nr, nc) {
  v <- readBin(path, what = "double", n = nr * nc, size = 8, endian = "little")
  matrix(v, nrow = nr, ncol = nc)
}

# The same deviation the Rust comparator records: the largest relative gap,
# floored so that entries which are zero on both sides are not counted as equal.
#
# Non-finite entries need care. A rank-deficient column leaves `NaN` in both the
# harness's output and the package's, at the same position, and that is an
# *agreement*: the two paths agree the column is not estimable. So finiteness is
# compared as a pattern, and only a position where exactly one side is finite
# counts as a disagreement.
deviation <- function(got, want) {
  if (!identical(dim(got), dim(want))) return(Inf)
  fin_g <- is.finite(got)
  fin_w <- is.finite(want)
  if (!identical(fin_g, fin_w)) return(Inf)
  g <- got[fin_g]
  w <- want[fin_w]
  if (!length(g)) return(0)
  scale <- pmax(pmax(abs(g), abs(w)), 1e-300)
  d <- abs(g - w) / scale
  d[g == w] <- 0
  if (any(!is.finite(d))) return(Inf)
  max(d)
}

# rtol per quantity, from crates/ancombc2-core/src/golden.rs
RTOL <- c(beta = 1e-8, se = 1e-7)

results <- list()
for (cell in cells$name) {
  gdir <- file.path(golden_root, cell)
  manifest <- jsonlite::fromJSON(file.path(gdir, "manifest.json"))
  cfg_path <- Sys.glob(file.path(here, "validation", "matrix", "fixtures", "*",
                                 sprintf("config-%s.json", cell)))
  if (length(cfg_path) != 1L) {
    results[[cell]] <- list(status = "SKIP", note = "no unique input group")
    next
  }
  fdir <- dirname(cfg_path)
  cfg <- jsonlite::fromJSON(cfg_path, simplifyVector = FALSE)

  counts <- as.matrix(utils::read.delim(file.path(fdir, "counts.tsv"),
                                        row.names = 1, check.names = FALSE))
  meta <- utils::read.delim(file.path(fdir, "meta.tsv"), row.names = 1,
                            check.names = FALSE)
  meta$group <- factor(meta$group, levels = sort(unique(meta$group)))
  ff <- paste(readLines(file.path(fdir, "formula.txt"), warn = FALSE), collapse = " ")

  args <- list(
    data = counts,
    meta_data = meta,
    fix_formula = ff,
    p_adj_method = cfg$p_adj_method,
    pseudo = as.numeric(cfg$pseudo),
    pseudo_sens = isTRUE(cfg$pseudo_sens),
    conservative = isTRUE(cfg$conservative),
    prv_cut = as.numeric(cfg$prv_cut),
    lib_cut = as.numeric(cfg$lib_cut),
    s0_perc = as.numeric(cfg$s0_perc),
    group = cfg$group,
    struc_zero = isTRUE(cfg$struc_zero),
    neg_lb = isTRUE(cfg$neg_lb),
    alpha = as.numeric(cfg$alpha),
    global = isTRUE(cfg$global),
    pairwise = isTRUE(cfg$pairwise),
    n_cl = 1L,
    verbose = FALSE,
    # These must stay *lists*: the package reads them with `$`, so handing it a
    # matrix (which is what `do.call(rbind, ...)` produces) fails with "$
    # operator is invalid for atomic vectors".
    iter_control = numify(cfg$iter_control),
    em_control = numify(cfg$em_control),
    mdfdr_control = list(fwer_ctrl_method = cfg$mdfdr_control$fwer_ctrl_method,
                         B = as.numeric(cfg$mdfdr_control$B))
  )

  r <- tryCatch(suppressWarnings(do.call(ancombc2, args)),
                error = function(e) e)
  if (inherits(r, "error")) {
    results[[cell]] <- list(status = "ERROR", note = conditionMessage(r))
    next
  }

  # `res` carries one column per fixed effect, named `lfc_<term>` / `se_<term>`,
  # so the package's own labels are what the golden's `fix_eff` columns are
  # matched on.
  terms <- manifest$fix_eff$value

  # Rows are *not* in the same order or the same count: a sparse cell retains 69
  # of its 100 taxa, and which 69 is itself a result (`taxa_retained`). So the
  # comparison is keyed on the taxon id, and a disagreement about the retained
  # set is reported as its own failure rather than as a numeric one.
  want_taxa <- manifest$taxa_retained$value
  if (!("taxon" %in% names(r$res))) {
    results[[cell]] <- list(status = "ERROR", note = "res has no taxon column")
    next
  }
  got_taxa <- as.character(r$res$taxon)
  if (!setequal(want_taxa, got_taxa)) {
    results[[cell]] <- list(
      status = "FAIL",
      note = sprintf("retained set differs: golden %d taxa, package %d; symmetric difference %d",
                     length(want_taxa), length(got_taxa),
                     length(setdiff(union(want_taxa, got_taxa),
                                    intersect(want_taxa, got_taxa)))))
    next
  }
  row_of <- match(want_taxa, got_taxa)

  devs <- c()
  missing_col <- NA_character_
  for (spec in list(list(nm = "beta", pre = "lfc_"), list(nm = "se", pre = "se_"))) {
    m <- manifest[[spec$nm]]
    want <- read_f64(file.path(gdir, m$file), m$nr, m$nc)
    got <- matrix(NA_real_, nrow = length(want_taxa), ncol = length(terms))
    for (j in seq_along(terms)) {
      col <- paste0(spec$pre, terms[j])
      if (!(col %in% names(r$res))) {
        missing_col <- col
        break
      }
      got[, j] <- r$res[[col]][row_of]
    }
    if (!is.na(missing_col)) break
    devs[spec$nm] <- deviation(got, want)
  }

  if (!is.na(missing_col)) {
    results[[cell]] <- list(status = "FAIL",
                            note = sprintf("res has no column %s", missing_col))
    next
  }
  ok <- all(devs <= RTOL[names(devs)])
  results[[cell]] <- list(status = if (isTRUE(ok)) "PASS" else "FAIL",
                          beta = devs[["beta"]], se = devs[["se"]])
}

cat(sprintf("%-32s %-6s %10s %10s\n", "cell", "status", "beta dev", "se dev"))
for (cell in names(results)) {
  x <- results[[cell]]
  if (is.null(x$beta)) {
    cat(sprintf("%-32s %-6s %s\n", cell, x$status, substr(x$note %||% "", 1, 66)))
  } else {
    cat(sprintf("%-32s %-6s %10.2e %10.2e\n", cell, x$status, x$beta, x$se))
  }
}

n_pass <- sum(vapply(results, function(x) x$status == "PASS", logical(1)))
n_fail <- sum(vapply(results, function(x) x$status == "FAIL", logical(1)))
n_skip <- sum(vapply(results, function(x) x$status %in% c("SKIP", "ERROR"), logical(1)))
cat(sprintf("\n%d cell(s): %d PASS, %d FAIL, %d skipped/errored\n",
            length(results), n_pass, n_fail, n_skip))
cat(sprintf("contract: rtol %g for beta, %g for se\n", RTOL[["beta"]], RTOL[["se"]]))

if (n_fail > 0L || n_skip > 0L) quit(status = 1L)
