//! Layer 1, second half: the golden **fixture matrix** of PLAN.md section 5.5.
//!
//! The four committed fixtures (`validation/fixtures/fx01`..`fx04`) are a handful
//! of shapes with a few settings each. PLAN.md asks for a *matrix* over shape,
//! sparsity, predictor type, covariate count and interactions, group balance,
//! structural zeros, pseudo-count, sensitivity on/off, conservative on/off and
//! the adjustment method. The cells are declared in `reference/R/fixture_matrix.R`,
//! generated by `scripts/generate_matrix_goldens.R`, and asserted here.
//!
//! Three things this suite is for, beyond "it runs":
//!
//! * **Every axis level is actually reached.** A cell that silently tested
//!   nothing -- a 10x10 table with a 5-group factor and 10 covariates, say --
//!   would pass while covering none of the thing it was named for. `the_matrix`
//!   therefore checks the *declared* matrix against the axes PLAN.md lists, and
//!   the generated `cells.json` is read back here so the check runs against what
//!   was generated rather than against the R source that declared it.
//! * **The config-only axes are isolated.** `pseudo` and `p_adj_method` change
//!   the answer without changing the data, so every cell in those sweeps must
//!   analyse the *same* table. If one drifted onto its own data, a failure would
//!   not say whether the configuration or the estimator broke.
//! * **A failure names its cell.** The cell name is the whole address of the
//!   configuration, so the report leads with it.

mod golden;

use ancombc2_core::ancombc2_run_named;
use golden::{compare_core, matrix_manifest, read_golden_at, GoldenSet};

/// Everything the matrix needs to know about a cell, read from the generated
/// `cells.json` rather than hard-coded, so a cell added on the R side is picked
/// up here without touching this file.
#[derive(Debug, Clone)]
struct CellInfo {
    name: String,
    inputs: String,
    n_tax: usize,
    n_samp: usize,
    n_group: usize,
    zero_rate: f64,
    struc_zero: bool,
    n_cont: usize,
    predictor: String,
    interact: bool,
    balanced: bool,
    pseudo: f64,
    p_adj_method: String,
    pseudo_sens: bool,
    conservative: bool,
    rank_deficient_cap: f64,
}

fn matrix_cells() -> Vec<CellInfo> {
    let cells = matrix_manifest();
    cells
        .into_iter()
        .map(|c| CellInfo {
            name: c.string("name"),
            inputs: c.string("inputs"),
            n_tax: c.number("n_tax") as usize,
            n_samp: c.number("n_samp") as usize,
            n_group: c.number("n_group") as usize,
            zero_rate: c.number("zero_rate"),
            struc_zero: c.boolean("struc_zero"),
            n_cont: c.number("n_cont") as usize,
            predictor: c.string("predictor"),
            interact: c.boolean("interact"),
            balanced: c.boolean("balanced"),
            pseudo: c.number("pseudo"),
            p_adj_method: c.string("p_adj_method"),
            pseudo_sens: c.boolean("pseudo_sens"),
            conservative: c.boolean("conservative"),
            rank_deficient_cap: c.number("rank_deficient_cap"),
        })
        .collect()
}

/// Run one cell and hold it to the same contract as the four committed fixtures.
fn run_cell(c: &CellInfo) {
    let f = golden::load_matrix_fixture(&c.inputs, &c.name);
    let g: GoldenSet = read_golden_at(&format!("validation/matrix/golden/{}", c.name));
    let r = ancombc2_run_named(
        &f.counts,
        &f.design,
        Some(&f.group),
        &f.cfg,
        &f.taxon_names,
        &f.sample_names,
    )
    .unwrap_or_else(|e| {
        panic!(
            "matrix cell {}: the run failed: {e}\n  ({} x {}, {} groups, {} covariates, \
             {}, zero_rate {}, struc_zero {}, pseudo {}, sens {}, {} , {})",
            c.name,
            c.n_tax,
            c.n_samp,
            c.n_group,
            c.n_cont,
            c.predictor,
            c.zero_rate,
            c.struc_zero,
            c.pseudo,
            c.pseudo_sens,
            if c.conservative {
                "conservative"
            } else {
                "nonconservative"
            },
            c.p_adj_method
        )
    });

    // The same rank-deficient scoping the committed fixtures use, computed per
    // taxon set because the two `.iter_mle` calls see different responses.
    let design = f.design.select_rows(&r.core.samples);
    let mask = golden::RankDeficientMask::for_run(&design, &r.core.y1, &r.core.y2, &f.group_name);
    // The Level A pattern assignment, before anything numeric: if the two sides
    // disagree about which taxa share a QR, every coefficient below is being
    // compared across different factorisations, and the first thing to establish
    // is that they are not.
    golden::compare_pattern_assignment(&golden::cell_golden_dir(&c.name), &r.core);
    // The sidecar checks run *after* the numeric comparison, and that order is
    // deliberate. The sidecars (`em_mixture`, `convergence_trace`) assert on
    // quantities that `compare_core` may only *report* -- the E-M's outputs are
    // indirect whenever a rank-deficient class is present -- so running them first
    // meant a sidecar failure pre-empted the numeric report and hid which inputs
    // were behind it. A cell that diverges should print everything the numeric
    // layer knows before anything aborts.
    if let Some(d) = compare_core(&g, &r, &mask, &design, f.cfg.p_adj_method) {
        panic!(
            "matrix cell {} diverges from the ANCOMBC 2.15.2 oracle:\n{d}\n({})",
            c.name,
            mask.summary()
        );
    }
    golden::compare_em_mixture(&golden::cell_golden_dir(&c.name), &r.core);
    golden::compare_convergence_trace(&golden::cell_golden_dir(&c.name), &r.core);
    assert!(
        !mask.over_budget_with(c.rank_deficient_cap),
        "matrix cell {}: {} -- a class exceeded its declared ceiling of {:.0}% \
         (rank-deficient); investigate rather than raise the cap",
        c.name,
        mask.summary(),
        c.rank_deficient_cap * 100.0
    );
}

#[test]
fn the_matrix_holds_the_declared_cells_to_the_golden_contract() {
    let cells = matrix_cells();
    assert!(
        cells.len() >= 30,
        "the matrix has only {} cells; PLAN.md section 5.5 lists ten axes and a \
         matrix that small cannot cover them",
        cells.len()
    );
    let mut failures: Vec<String> = Vec::new();
    for c in &cells {
        // A missing golden directory is reported as a failure rather than a
        // panic, so one ungenerated cell does not hide the other 37.
        let gdir = format!(
            "{}/validation/matrix/golden/{}/manifest.json",
            golden::repo_root().display(),
            c.name
        );
        if !std::path::Path::new(&gdir).exists() {
            failures.push(format!(
                "{}: no golden at {gdir} -- run \
                 `Rscript scripts/generate_matrix_goldens.R {}`",
                c.name, c.name
            ));
            continue;
        }
        run_cell(c);
    }
    assert!(
        failures.is_empty(),
        "{} of {} matrix cells have no golden:\n  {}",
        failures.len(),
        cells.len(),
        failures.join("\n  ")
    );
}

/// The matrix must actually cover the axes PLAN.md names, and it must do so from
/// the *generated* manifest.
///
/// A suite that asserts "the cells I was told about pass" is only as good as the
/// declaration feeding it. This reads `cells.json` -- written by the generator --
/// and checks the levels are present, so a matrix that lost an axis, or a cell
/// whose levels were overridden by accident, fails here rather than passing
/// quietly on a narrower sweep than the plan asks for.
#[test]
fn the_matrix_covers_every_axis_level_the_plan_lists() {
    let cells = matrix_cells();
    let has = |pred: &dyn Fn(&CellInfo) -> bool| cells.iter().any(pred);
    let mut missing: Vec<&str> = Vec::new();

    // shape: 10x10 / 100x30 / 1000x100 / 10000x500
    for (t, s) in [(10usize, 10usize), (100, 30), (1000, 100), (10000, 500)] {
        if !has(&|c: &CellInfo| c.n_tax == t && c.n_samp == s) {
            missing.push("shape");
        }
    }
    // sparsity: zero-free / 10 / 50 / 90 %
    for z in [0.0f64, 0.1, 0.5, 0.9] {
        if !has(&|c: &CellInfo| (c.zero_rate - z).abs() < 1e-12) {
            missing.push(match z {
                0.0 => "sparsity zero-free",
                0.1 => "sparsity 10%",
                0.5 => "sparsity 50%",
                _ => "sparsity 90%",
            });
        }
    }
    // predictors: continuous / binary / 3-group / 5-group
    if !has(&|c: &CellInfo| c.predictor == "continuous") {
        missing.push("continuous predictor");
    }
    if !has(&|c: &CellInfo| c.predictor == "binary") {
        missing.push("binary predictor");
    }
    if !has(&|c: &CellInfo| c.n_group == 3) {
        missing.push("3-group predictor");
    }
    if !has(&|c: &CellInfo| c.n_group == 5) {
        missing.push("5-group predictor");
    }
    // covariates: 1 / 5 / 10, and interactions
    for k in [1usize, 5, 10] {
        if !has(&|c: &CellInfo| c.n_cont == k) {
            missing.push("covariate count");
        }
    }
    if !has(&|c: &CellInfo| c.interact) {
        missing.push("group:x1 interaction");
    }
    // groups: balanced / unbalanced
    if !has(&|c: &CellInfo| c.balanced) {
        missing.push("balanced groups");
    }
    if !has(&|c: &CellInfo| !c.balanced) {
        missing.push("unbalanced groups");
    }
    // structural zeros present / absent
    if !has(&|c: &CellInfo| c.struc_zero) {
        missing.push("structural zeros present");
    }
    if !has(&|c: &CellInfo| !c.struc_zero) {
        missing.push("structural zeros absent");
    }
    // pseudo: 0 / 0.1 / 0.5 / 1.0
    for p in [0.0f64, 0.1, 0.5, 1.0] {
        if !has(&|c: &CellInfo| (c.pseudo - p).abs() < 1e-12) {
            missing.push("pseudo-count level");
        }
    }
    // sensitivity on / off, and conservative on / off
    if !has(&|c: &CellInfo| !c.pseudo_sens) {
        missing.push("sensitivity off");
    }
    if !has(&|c: &CellInfo| c.pseudo_sens && c.conservative) {
        missing.push("sensitivity on, conservative");
    }
    if !has(&|c: &CellInfo| c.pseudo_sens && !c.conservative) {
        missing.push("sensitivity on, non-conservative");
    }
    // all seven adjustment methods
    for m in [
        "holm",
        "hochberg",
        "hommel",
        "bonferroni",
        "BH",
        "BY",
        "none",
    ] {
        if !has(&|c: &CellInfo| c.p_adj_method == m) {
            missing.push("adjustment method");
        }
    }
    assert!(
        missing.is_empty(),
        "the generated fixture matrix is missing required axis levels: {}\n  \
         the matrix is declared in reference/R/fixture_matrix.R; add the cells \
         rather than relaxing this check",
        dedup(missing).join(", ")
    );
}

/// The config-only sweeps must share one table, or they are not testing the
/// configuration.
///
/// `pseudo` and `p_adj_method` do not change the data. A sweep over them is only
/// a clean test of the configuration if every cell analyses the same counts, so
/// a failure points at the configuration rather than at the estimator *and* the
/// data. This is checked against the generated manifest's `inputs` field.
#[test]
fn the_config_only_sweeps_share_one_table() {
    let cells = matrix_cells();
    // Matched by *name*, not by axis value: the core cell also has `pseudo = 0`,
    // so a value predicate pulled in all 28 other tables and the check reported
    // the whole matrix as one sweep.
    let inputs_named = |prefix: &str| -> Vec<String> {
        cells
            .iter()
            .filter(|c| c.name.starts_with(prefix))
            .map(|c| c.inputs.clone())
            .collect()
    };
    let sweeps: Vec<(&str, String, Vec<String>)> = vec![
        (
            "pseudo-count",
            "pseudo-".to_string(),
            inputs_named("pseudo-"),
        ),
        (
            "adjustment method",
            "adjust-".to_string(),
            inputs_named("adjust-"),
        ),
    ];
    for (label, prefix, mut distinct) in sweeps {
        distinct.sort_unstable();
        distinct.dedup();
        assert_eq!(
            distinct.len(),
            1,
            "the {label} sweep (`{prefix}`) analyses {} different tables \
             ({distinct:?}); a config-only axis must not change the data, or a \
             failure cannot be attributed to the configuration",
            distinct.len()
        );
    }
}

/// A sweep that varies an axis must not vary anything else, or it is two sweeps
/// at once.
///
/// This is the same discipline as the config-only check, applied to the data
/// axes: the `predictor-*` cells should differ only in predictor type, the
/// `sparsity-*` cells only in zero rate, and so on. A `modifyList` typo in the
/// R declaration that leaked an extra axis would otherwise pass silently.
#[test]
fn each_sweep_varies_exactly_one_axis() {
    let cells = matrix_cells();
    let mut problems: Vec<String> = Vec::new();
    /// Every axis of a cell except the ones the sweep legitimately varies.
    ///
    /// The swept axes are excluded or the check is vacuous -- the cells in a
    /// sweep differ *by* those axes, so including them would report every sweep
    /// as broken. A sweep may legitimately vary more than one, and `predictor-`
    /// does: PLAN.md's "continuous/binary/3-group/5-group predictors" is a
    /// covariate's *type* and a factor's *cardinality* in one list, so those
    /// cells differ in `predictor` and `n_group` together. Naming both keeps the
    /// reader's `predictor-3group` while still catching a third axis moving.
    fn axes_except(c: &CellInfo, swept: &[&str]) -> String {
        let mut v: Vec<(&str, String)> = vec![
            ("n_tax", c.n_tax.to_string()),
            ("n_samp", c.n_samp.to_string()),
            ("n_group", c.n_group.to_string()),
            ("zero_rate", format!("{:.15}", c.zero_rate)),
            ("struc_zero", c.struc_zero.to_string()),
            ("n_cont", c.n_cont.to_string()),
            ("predictor", c.predictor.clone()),
            ("interact", c.interact.to_string()),
            ("balanced", c.balanced.to_string()),
            ("pseudo", format!("{:.15}", c.pseudo)),
            ("p_adj_method", c.p_adj_method.clone()),
            ("pseudo_sens", c.pseudo_sens.to_string()),
            ("conservative", c.conservative.to_string()),
        ];
        v.retain(|(k, _)| !swept.contains(k));
        v.sort_unstable();
        v.into_iter()
            .map(|(k, val)| format!("{k}={val}"))
            .collect::<Vec<_>>()
            .join(" ")
    }

    fn check(prefix: &str, swept: &[&str], cells: &[CellInfo], problems: &mut Vec<String>) {
        let group: Vec<&CellInfo> = cells
            .iter()
            .filter(|c| c.name.starts_with(prefix))
            .collect();
        if group.len() < 2 {
            problems.push(format!(
                "{prefix}: only {} cell(s), so nothing is swept",
                group.len()
            ));
            return;
        }
        let first = axes_except(group[0], swept);
        for c in &group[1..] {
            let got = axes_except(c, swept);
            if got != first {
                problems.push(format!(
                    "{prefix}: {} differs from {} outside the {swept:?} axis it is \
                     named for\n    {got}\n    {first}",
                    c.name, group[0].name
                ));
            }
        }
    }

    for (prefix, swept) in [
        ("sparsity-", &["zero_rate"][..]),
        // PLAN.md lists "continuous/binary/3-group/5-group predictors" as one
        // axis; in the implementation that is a covariate's type and a factor's
        // cardinality, so both move together in this sweep.
        ("predictor-", &["predictor", "n_group"][..]),
        // "1/5/10 covariates and interactions" is one axis in PLAN.md, so the
        // interaction cell is part of this sweep and moves `interact` with
        // `n_cont`.
        ("covariates-", &["n_cont", "interact"][..]),
        ("groups-", &["balanced"][..]),
        ("struczero-", &["struc_zero"][..]),
        // `conservative` is only reachable with `pseudo_sens = TRUE` -- the flag
        // selects which refit loop runs, so "conservative = FALSE, sens = FALSE"
        // is the same run twice and cannot be a cell. The conservative on/off
        // axis is therefore *nested* inside sens=on, and the coverage test
        // asserts both halves are present rather than this sweep pairing them.
        ("sensitivity-", &["pseudo_sens", "conservative"][..]),
        ("adjust-", &["p_adj_method"][..]),
        // `signal_frac` is not an axis of its own in the manifest -- it is not
        // recorded per cell -- so the shape sweep is exempt from it by
        // construction. The two shape cells that need fewer signals set it, and
        // a 10000x500 table with 10% of taxa signal is not comparable to a 10x10
        // one with 30%.
        ("shape-", &["n_tax", "n_samp"][..]),
    ] {
        check(prefix, swept, &cells, &mut problems);
    }
    assert!(
        problems.is_empty(),
        "a sweep varies more than the axis it is named for:\n  {}",
        problems.join("\n  ")
    );
}

/// The conservative on/off pair must exist, and it must exist *within* the
/// sensitivity analysis being on.
///
/// `conservative` selects between two refit loops that only run when
/// `pseudo_sens` is set, so a `conservative = FALSE, pseudo_sens = FALSE` cell
/// would be a duplicate of the same run rather than a test of anything. This
/// checks the axis is actually swept where it can be, instead of trusting the
/// cell names to have got it right.
#[test]
fn the_conservative_axis_is_swept_within_the_sensitivity_analysis() {
    let cells = matrix_cells();
    let on_conservative = cells.iter().any(|c| c.pseudo_sens && c.conservative);
    let on_nonconservative = cells.iter().any(|c| c.pseudo_sens && !c.conservative);
    let off = cells.iter().any(|c| !c.pseudo_sens);
    let mut problems: Vec<&str> = Vec::new();
    if !off {
        problems.push("no cell has the sensitivity analysis off");
    }
    if !on_conservative {
        problems.push("no cell has the sensitivity analysis on and conservative");
    }
    if !on_nonconservative {
        problems.push("no cell has the sensitivity analysis on and non-conservative");
    }
    // A cell with `conservative = FALSE` but the analysis off is the unreachable
    // combination; it would silently be a duplicate run.
    for c in &cells {
        if !c.pseudo_sens && !c.conservative {
            problems.push("a cell sets conservative without the sensitivity analysis");
        }
    }
    assert!(
        problems.is_empty(),
        "the conservative axis is not properly covered: {}",
        problems.join("; ")
    );
}

fn dedup(mut v: Vec<&str>) -> Vec<&str> {
    v.sort_unstable();
    v.dedup();
    v
}
