[package]
name = "ancombc2-core"
description = "Numerically compatible fixed-effects ANCOM-BC2 numerical core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
ancombc2-stats.workspace = true
rayon.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
rayon.workspace = true

[lib]
name = "ancombc2_core"
path = "src/lib.rs"
